name: Set GX Mobile ios configure matrix
author: Sello
description: 'Get scheme list from tag'
inputs:
  tag:
    description: 'tag'
    required: true
    default: ''
outputs:
  matrix:
    description: 'Get scheme list'
    value: ${{ steps.set-value.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Set Matrix
      id: set-value
      shell: bash
      run: |
        echo "matrix=[\"qa\",\"stage\"]" >> $GITHUB_OUTPUT

        TAG=${{inputs.tag}}

        if [[ "${TAG}" == "all2" ]]; then
          echo "matrix=[\"qa2\",\"stage\"]" >> $GITHUB_OUTPUT
        fi
