default_platform(:ios)

lane :build do

  version = get_version_number(xcodeproj: "CI-CD-Test.xcodeproj")
  newVersion = ENV["TAG"].split('v')[1].split('-')[0].strip
  release_tag_name = ENV["TAG"]

  if version != newVersion 
    increment_version_number_in_plist(
      version_number: newVersion,
      xcodeproj: "CI-CD-Test.xcodeproj",
      target: "CI-CD-Test",
      plist_build_setting_support: true
    )
  end

  increment_build_number

  versionNumber = get_version_number(xcodeproj: "CI-CD-Test.xcodeproj")
  buildNumber = get_build_number(xcodeproj: "CI-CD-Test.xcodeproj")
  release_tag_name["-"] = "_"

  github_release = set_github_release(
    repository_name: "sello-lee/CI-CD-Test",
    name: "#{release_tag_name} (#{buildNumber})",
    api_token: ENV["GIT_TOKEN"],
    tag_name: release_tag_name,
    description: "디스크립션",
   )

end
