name: Set GX Mobile ios configure
author: Bolt lee
description: 'Prepare gx github aciton value'
inputs:
  xcode-version:
    description: '' # xcode-version
    required: true
    default: '13.1'
  ENCRYPTED_CERT_FILE_PATH:
    description: '' # certificate
    required: false
    default: ${{ '.github/secrets/certs.p12.gpg' }}
  DECRYPTED_CERT_FILE_PATH:
    description: '' # certificate
    required: false
    default: ${{ '.github/secrets/certs.p12' }}
  CERT_ENCRYPTION_KEY:
    description: '' # gpg로 파일 암호화할 때 사용한 암호
    required: true
    default: ''
  ENCRYPTED_PROVISION_FILE_PATH:
    description: '' # provisioning
    required: true
    default: ''
  DECRYPTED_PROVISION_FILE_PATH:
    description: '' # provisioning
    required: true
    default: ''
  PROVISIONING_ENCRYPTION_KEY:
    description: '' # provisioning # gpg로 파일 암호화할 때 사용한 암호
    required: true
    default: ''
  CERT_EXPORT_KEY:
    description: '' # certification export key
    required: true
    default: ''
  KEYCHAIN:
    description: '' # certification export key
    required: false
    default: ${{ 'test.keychain' }}
  KEYCHAIN_PWD:
    description: '' # certification export key
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: setup xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}
    - name: Configure Keychain and Code Signing
      shell: bash
      run: |
        gpg -d -o  ${{ inputs.DECRYPTED_CERT_FILE_PATH }} --pinentry-mode=loopback --passphrase ${{ inputs.CERT_ENCRYPTION_KEY }} ${{ inputs.ENCRYPTED_CERT_FILE_PATH }}
        gpg -d -o ${{ inputs.DECRYPTED_PROVISION_FILE_PATH }} --pinentry-mode=loopback --passphrase ${{ inputs.PROVISIONING_ENCRYPTION_KEY }} ${{ inputs.ENCRYPTED_PROVISION_FILE_PATH }}

        security create-keychain -p "${{ inputs.KEYCHAIN_PWD }}" ${{ inputs.KEYCHAIN }}
        security list-keychains -s ${{ inputs.KEYCHAIN }}
        security default-keychain -s ${{ inputs.KEYCHAIN }}
        security unlock-keychain -p "${{ inputs.KEYCHAIN_PWD }}" ${{ inputs.KEYCHAIN }}
        security set-keychain-settings

        security import ${{ inputs.DECRYPTED_CERT_FILE_PATH }} -k ${{ inputs.KEYCHAIN }} -P ${{ inputs.CERT_EXPORT_KEY }} -A
        security set-key-partition-list -S apple-tool:,apple: -s -k "${{ inputs.KEYCHAIN_PWD }}" ${{ inputs.KEYCHAIN }}

        mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
        echo `ls .github/secrets/*.mobileprovision`
          for PROVISION in `ls .github/secrets/*.mobileprovision`
          do
            UUID=`/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i ./$PROVISION)`
          cp "./$PROVISION" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
        done
