name: Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          xcodebuild build -project CI-CD-Test/CI-CD-Test.xcodeproj
