name: DeleteKeyChain
on:
  workflow_dispatch:

jobs:
  remove:
    runs-on: self-hosted
    steps:
      - shell: bash
        if: always()
        run: |
          security delete-keychain TestApp-QA.keychain
      - shell: bash
        if: always()
        run: |
          security delete-keychain TestApp-Stage.keychain
