name: FastlaneTest
on:
  workflow_dispatch:

jobs:
  fastlane-action:
    runs-on: self-hosted
    env:
      scheme_list: ${{ fromJson(strategy.matrix.environment) }}
    strategy:
      matrix:
        environment: ["qa", "stage"]
    steps:
      - uses: maierj/fastlane-action@v2.2.0
        with:
          lane: splitTest
        env:
          DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
          SCHEME_ALL_LIST: ${{ env.scheme_list }}
          SCHEME: ${{ matrix.environment }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          BUILD_NUMBER: ${{ vars.BUILD_NUMBER }}
