name: FastlaneTest
on:
  workflow_dispatch:
  push:
    tags:
      - 'qa'
      - 'stage'

jobs:
  fastlane-action:
    runs-on: self-hosted
    strategy:
      matrix:
        environment: ["qa","stage"]
  	steps: 
  	  - uses: maierj/fastlane-action@v2.2.0
  	    with:
  	      lane: splitTest
  	    env: 
  	      DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
          SCHEME_ALL_LIST: ${{ strategy.matrix.environment }}
          SCHEME: ${{ github.ref_name }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          BUILD_NUMBER: ${{ vars.BUILD_NUMBER }}
