name: KeyChainTest
on:
  workflow_dispatch:

jobs:
  remove:
    runs-on: self-hosted
    steps:
      - shell: bash
        run: |
          security delete-keychain TestApp-QA.keychain
          security delete-keychain TestApp-Stage.keychain
