name: Test

on:
  # workflow가 실행되는 경우 (main 브랜치에 push하는 경우, action 탭에서 수동으로 동작시키는 경우)
  push:
    branches: [ "main" ]
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    # job이 실행될 환경 - 최신 mac os
    runs-on: macos-latest

    steps:
      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode.app"
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Echo test
        run: echo Hello, world!

