name: Test

on:
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Run tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  test:
    name: Run tests
    runs-on: ubuntu-22.04
    needs: check
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: echo and sleep
        run: |
          echo Hello, world!
          sleep 15s
  
    
