name: Test and Wait

on:
  workflow_dispatch:
  
jobs:
  test1:
    name: Run tests1
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'
      - name: Checkout project
        uses: actions/checkout@v3
      - name: echo and sleep1
        run: |
          echo Hello, world!
          sleep 20s

