name: Test and Wait

on:
  push:
  workflow_dispatch:
  
jobs:

  consecutiveness:
    runs-on: ubuntu-latest
    steps:
    - uses: mktcode/consecutive-workflow-action@e2e008186aa210faacd68ec30f6ac236f7e2f435
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Run tests
    runs-on: ubuntu-22.04
    needs: wait
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: echo and sleep
        run: |
          echo Hello, world!
          sleep 20s


