name: Test

on:
  push:
  workflow_dispatch:
  
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: echo and sleep
        run: |
          echo Hello, world!
          sleep 15s
  
    
