name: Test and Wait

on:
  push:
  workflow_dispatch:
  
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    needs: wait
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: echo and sleep
        run: |
          echo Hello, world!
          sleep 15s
  wait:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for tests to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: echooo
        run: echo hiii

